version: "3.4"

x-ros-master-uri-env: &ros-master-uri-env ROS_MASTER_URI=http://${ROS_MASTER_DOMAIN:-ros_melodic}:11311
# host.docker.internal:0を使う場合以下は不要, rwオプションの使用でコンテナ内でファイルの書き込みが可能に
x-x11-mapping: &x11-mapping /tmp/.X11-unix:/tmp/.X11-unix:rw

x-common-setting: &common-setting
  tty: true
  # TODO: moveitの実行時のために特権つけてるが限定的な権限に置き換えたい
  privileged: true
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
  command: bash -c "catkin clean -by && catkin build && /bin/bash"

#########################################################################################################

services:
  ros_melodic:
    <<: *common-setting
    build:
      context: .
      dockerfile: ./docker/melodic/Dockerfile
      args:
        BUILD_USER: ${USER} 
    image: yamachaso/ros_melodic:latest
    container_name: ros_melodic
    volumes:
      - *x11-mapping
      - ./src/melodic/:/home/${USER}/catkin_ws/src
      - ./outputs/melodic/:/home/${USER}/catkin_ws/outputs
      - ./src/noetic/detect/action:/home/${USER}/catkin_ws/src/detect/action
      - ./src/noetic/detect/msg:/home/${USER}/catkin_ws/src/detect/msg
      - ./src/noetic/detect/srv:/home/${USER}/catkin_ws/src/detect/srv
      - ./src/noetic/detect/package.xml:/home/${USER}/catkin_ws/src/detect/package.xml
      - ./src/noetic/detect/CMakeLists.txt:/home/${USER}/catkin_ws/src/detect/CMakeLists.txt
      - /dev/input/js0:/dev/input/js0
    # portsの設定の必要性を感じていないが一応設定
    ports:
      - 11311 
    networks:
      ros_dev_external_with_hand: 
        ipv4_address: 192.168.11.51
    environment:
      - DISPLAY=${DISPLAY}
      - *ros-master-uri-env

  ros_noetic:
    <<: *common-setting
    build:
      context: .
      dockerfile: ./docker/noetic/Dockerfile
      args:
        BUILD_USER: ${USER}
    image: yamachaso/ros_noetic:latest
    container_name: ros_noetic
    volumes:
      - *x11-mapping
      - ./src/noetic/:/home/${USER}/catkin_ws/src
      - ./outputs/noetic/:/home/${USER}/catkin_ws/outputs
    networks:
      ros_dev_external_with_hand: 
        ipv4_address: 192.168.11.52
    environment:
      - DISPLAY=${DISPLAY}
      - *ros-master-uri-env
      - PYTHONPATH=/home/${USER}/catkin_ws/src/detect/scripts:${PYTHONPATH}

networks:
  ros_dev_external_with_hand:
    external: true
